<?php
// $Id$


module_load_include('inc', 'crumbs', 'crumbs.api');

module_load_include('inc', 'crumbs', 'crumbs.menu');
module_load_include('inc', 'crumbs', 'crumbs.taxonomy');
module_load_include('inc', 'crumbs', 'crumbs.path');
module_load_include('inc', 'crumbs', 'crumbs.pathauto');
module_load_include('inc', 'crumbs', 'crumbs.node');
module_load_include('inc', 'crumbs', 'crumbs.nodereference');
module_load_include('inc', 'crumbs', 'crumbs.crumbs');

function crumbs_perm() {
  return array('administer crumbs');
}


function crumbs_menu() {
  $items = array();
  $items['crumbs/node-type-dummy-path/%'] = array(
    'title' => 'Crumbs dummy path',
    'title callback' => 'check_plain',
    'page callback' => '_crumbs_donothing',
    'access callback' => '_crumbs_noaccess',
  );
  $items['admin/build/crumbs'] = array(
    'title' => 'Crumbs',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crumbs_admin_form'),
    'access arguments' => array('administer crumbs'),
    'file' => 'crumbs.admin.inc',
  );
  return $items;
}


function _crumbs_donothing() {
  return '';
}

function _crumbs_noaccess() {
  return TRUE;
}


function crumbs_init() {
  $item = menu_get_item();
  $link_path = $item['href'];
  $trail = crumbs_build_trail($link_path, TRUE);
  _crumbs_set_trail($trail);
  $breadcrumb = crumbs_build_breadcrumb($trail);
  _crumbs_set_breadcrumb($breadcrumb);
  drupal_set_breadcrumb($breadcrumb);
  $finder = _crumbs_get_finder();
  $finder->invokeInit($trail);
}


function crumbs_build_breadcrumb($trail) {
  $breadcrumb = array();
  foreach ($trail as $path => $item) {
    $breadcrumb[] = $item->link();
  }
  return $breadcrumb;
}


function crumbs_preprocess_page(&$vars) {
  $trail = crumbs_get_trail();
  $vars['crumbs_trail'] = crumbs_get_trail();
  // Some modules call drupal_set_breadcrumb() with their own ideas of a
  // breadcrumb, and thus overwrite the breadcrumb set in crumbs_init(),
  // Thus, we need template_preprocess_page() to restore the crumbs crumb
  // for page rendering.
  $breadcrumb = crumbs_get_breadcrumb();
  $vars['breadcrumb'] = theme('breadcrumb', $breadcrumb);
  $finder = _crumbs_get_finder();
  $finder->invokePreprocessPage($vars, $trail);
}


function crumbs_get_trail() {
  return _crumbs_set_trail();
}


function _crumbs_set_trail($trail = NULL) {
  static $_trail;
  if (is_array($trail)) {
    $_trail = $trail;
  }
  else {
    return $_trail;
  }
}


function crumbs_get_breadcrumb() {
  return _crumbs_set_breadcrumb();
}


function _crumbs_set_breadcrumb($breadcrumb = NULL) {
  static $_breadcrumb;
  if (is_array($breadcrumb)) {
    $_breadcrumb = $breadcrumb;
  }
  else {
    return $_breadcrumb;
  }
}


function crumbs_build_trail($path) {
  $finder = _crumbs_get_finder();
  $trail = $finder->buildTrail($path);
  $trail_wrapped = array();
  foreach ($trail as $path => $extra) {
    $trail_wrapped[$path] = new crumbs_ItemWrapper_theme($extra);
  }
  return $trail_wrapped;
}


function _crumbs_get_finder() {
  static $_finder;
  if (!isset($_finder)) {
    $_finder = new _crumbs_TrailFinder();
  }
  return $_finder;
}




class _crumbs_TrailFinder {
  
  protected $_pluginEngine;
  
  function __construct() {
    $this->_pluginEngine = new _crumbs_PluginEngine();
  }
  
  
  function buildTrail($path) {
    $trail_reverse = array();
    $front_normal_path = drupal_get_normal_path(variable_get('site_frontpage', 'node'));
    $front_menu_item = menu_get_item($front_normal_path);
    while (strlen($path) && $path !== '<front>' && $path != $front_normal_path) {
      if (isset($trail_reverse[$path])) {
        // We found a loop! To prevent infinite recursion, we
        // remove the loopy paths from the trail and finish directly with <front>.
        while (isset($trail_reverse[$path])) {
          array_pop($trail_reverse);
        }
        break;
      }
      $menu_item = menu_get_item($path);
      $extra = (object)array(
        'title' => $menu_item['title'],
        'path' => $path,
        'item' => $menu_item,
        'alias' => drupal_get_path_alias($path),
      );
      $parent_path = $this->_findParentPath($path, $extra);
      if ($menu_item) {
        $this->_decorateItem($path, $extra, $trail_reverse);
        if (!$extra->skip_in_breadcrumb && $menu_item['access']) {
          $trail_reverse[$path] = $extra;
        }
      }
      if ($parent_path == $path) {
        // This is again a loop, but with just one step.
        // Not as evil as the other kind of loop.
        break;
      }
      $path = $parent_path;
    }
    unset($trail_reverse[$front_normal_path]);
    $trail_reverse['<front>'] = (object)array(
      'title' => $front_menu_item['title'],
      'path' => $front_normal_path,
      'item' => $front_menu_item,
    );
    $trail = array_reverse($trail_reverse);
    $this->_decorateTrail($trail);
    return $trail;
  }
  
  
  function invokeInit($trail) {
    $invokeAction = new _crumbs_InvokeAction_simple('init', array($trail));
    $this->_pluginEngine->invokeAll($invokeAction);
  }
  
  
  function invokePreprocessPage(&$vars, $trail) {
    $invokeAction = new _crumbs_InvokeAction_simple('preprocessPage', array(&$vars, $trail));
    $this->_pluginEngine->invokeAll($invokeAction);
  }
  
  
  /**
   * This function is called when the full trail has been built.
   * Other modules get a chance to modify the title.
   */
  protected function _decorateTrail(array $trail) {
    $trail_wrapped = array();
    foreach ($trail as $path => $extra) {
      $trail_wrapped[$path] = new crumbs_ItemWrapper_decorate($extra);
    }
    $invokeAction = new _crumbs_InvokeAction_simple('decorateTrail', array($trail_wrapped));
    $this->_pluginEngine->invokeAll($invokeAction);
  }
  
  
  protected function _decorateItem($path, stdClass $extra) {
    if ($extra->item) {
      $invokeAction = new _crumbs_InvokeAction_decorate($path, $extra);
      $this->_pluginEngine->invokeAll($invokeAction);
    }
  }
  
  
  protected function _findParentPath($path, stdClass $extra) {
    if ($extra->item) {
      $invokeAction = new _crumbs_InvokeAction_find($path, $extra);
      $this->_pluginEngine->invokeAll($invokeAction);
      $parent_path = $invokeAction->getParentPath();
      if ($parent_path) {
        return $parent_path;
      }
    }
    // fallback: chop off the last fragment of the system path.
    $fragments = explode('/', $path);
    return implode('/', array_slice($fragments, 0, -1));
  }
}


class _crumbs_PluginEngine {
  
  protected $_order;
  protected $_subkey_order = array();
  protected $_objects;
  protected $_wildcard_objects = array();
  protected $_subkey_wildcard_objects = array();
  
  function __construct() {
    $this->_order = _crumbs_get_settings();
    foreach ($this->_order as $order_key => $enabled) {
      list($object_key, $sub_key) = explode(':', $order_key, 2);
      $this->_subkey_order[$object_key][$sub_key] = $enabled;
    }
    $this->_objects = _crumbs_get_objects();
    foreach ($this->_objects as $object_key => $object) {
      if (isset($this->_order[$object_key])) {
        // do nothing
      }
      else if (isset($this->_order["$object_key:*"])) {
        $this->_subkey_wildcard_objects["$object_key:*"] = $object;
      }
      else {
        list($module, $instance_key) = explode('.', $object_key, 2);
        if ($this->_order["$module.*"]) {
          $this->_wildcard_objects["$module.*"][$instance_key] = $object;
        }
      }
    }
  }
  
  function invokeAll($invokeAction) {
    foreach ($this->_order as $order_key => $enabled) {
      if ($enabled) {
        list($object_key, $sub_key) = explode(':', $order_key, 2);
        list($module, $instance_key) = explode('.', $object_key, 2);
        $subkey_order = $this->_subkey_order[$object_key];
        if ($instance_key !== '*' && $object = $this->_objects[$object_key]) {
          $stop = $invokeAction->invoke($object, $object_key, $order_key, $subkey_order);
          if ($stop === TRUE) {
            return;
          }
        }
        else if ($instance_key === '*' && !isset($sub_key) && $objects = $this->_wildcard_objects[$object_key]) {
          foreach ($objects as $instance_key => $object) {
            $stop = $invokeAction->invoke($object, "$module.$instance_key", $order_key, $subkey_order);
            if ($stop === TRUE) {
              return;
            }
          }
        }
      }
    }
  }
}


class _crumbs_InvokeAction_simple {
  
  protected $_method;
  protected $_args;
  
  function __construct($method, $args) {
    $this->_method = $method;
    foreach (array_keys($args) as $i => $k) {
      $this->_args[$i] = &$args[$k];
    }
  }
  
  function invoke($object, $object_key, $order_key, $subkey_order) {
    $args = $this->_args;
    list($object_key, $sub_key) = explode(':', $order_key, 2);
    list($module, $instance_key) = explode('.', $object_key, 2);
    $args[] = $sub_key;
    $args[] = $subkey_order;
    $method = $this->_method;
    if (method_exists($object, $method)) {
      call_user_func_array(array($object, $method), $args);
    }
  }
}


class _crumbs_InvokeAction_find {
  
  protected $_path;
  protected $_item;
  protected $_method;
  protected $_parent_path;
  protected $_candidates = array();
  
  function __construct($path, $extra) {
    $this->_path = $path;
    $item = new crumbs_ItemWrapper_find($extra);
    $this->_item = $item;
    $this->_method = 'find__' . preg_replace('/[^a-z0-9]/', '_', strtolower($extra->item['path']));
  }
  
  function invoke($object, $object_key, $order_key, $subkey_order) {
    if (isset($this->_candidates[$order_key])) {
      $this->_parent_path = $this->_candidates[$order_key];
      return TRUE;
    }
    list($object_key, $sub_key) = explode(':', $order_key, 2);
    list($module, $instance_key) = explode('.', $object_key, 2);
    $path_method = $this->_method;
    foreach (array($path_method, 'find') as $method) {
      if (method_exists($object, $method)) {
        $result = $object->$method($this->_path, $this->_item, $subkey_order);
        if (is_array($result)) {
          foreach ($result as $x_sub_key => $parent_path) {
            if (!isset($subkey_order[$x_sub_key])) {
              $this->_candidates["$object_key:*"] = $parent_path;
            }
            else if ($subkey_order[$x_sub_key]) {
              $this->_candidates["$object_key:$x_sub_key"] = $parent_path;
            }
          }
        }
        else if (is_string($result)) {
          $this->_candidates[$order_key] = $parent_path;
        }
      }
    }
    if (isset($this->_candidates[$order_key])) {
      $this->_parent_path = $this->_candidates[$order_key];
      return TRUE;
    }
  }
  
  function getParentPath() {
    return $this->_parent_path;
  }
}


class _crumbs_InvokeAction_decorate {
  
  protected $_path;
  protected $_item;
  protected $_method;
  
  function __construct($path, $extra) {
    $this->_path = $path;
    $item = new crumbs_ItemWrapper_find($extra);
    $this->_item = $item;
    $this->_method = 'decorate__' . preg_replace('/[^a-z0-9]/', '_', strtolower($extra->item['path']));
  }
  
  function invoke($object, $object_key, $order_key, $subkey_order) {
    list($object_key, $sub_key) = explode(':', $order_key, 2);
    list($module, $instance_key) = explode('.', $object_key, 2);
    $path_method = $this->_method;
    foreach (array($path_method, 'decorate') as $method) {
      if (method_exists($object, $method)) {
        $result = $object->$method($this->_path, $this->_item, $sub_key, $subkey_order);
      }
    }
  }
}



function _crumbs_get_settings() {
  $settings = variable_get('crumbs', array());
  return is_array($settings) ? $settings : array();
}



function _crumbs_get_objects() {
  $sort_order = _crumbs_get_settings();
  $objects = array();
  $objects_enabled = array();
  $modules_enabled = array();
  foreach ($sort_order as $order_key => $enabled) {
    if ($enabled) {
      list($object_key, $sub_key) = explode(':', $order_key, 2);
      list($module, $instance_key) = explode('.', $object_key, 2);
      $objects_enabled[$object_key] = TRUE;
      $modules_enabled[$module] = TRUE;
    }
  }
  foreach (module_list(FALSE, TRUE) as $module) {
    $class = $module . '_class_CrumbsParentFinder';
    if (class_exists($class)) {
      if (method_exists($class, 'construct')) {
        // use the factory method.
        $result = call_user_func(array($class, 'construct'));
        if (is_object($result)) {
          $objects[$module] = $result;
        }
        else if (is_array($result)) {
          foreach ($result as $key => $object) {
            $objects["$module.$key"] = $object;
          }
        }
      } else {
        $objects[$module] = new $class;
      }
    }
  }
  foreach ($objects as $key => $object) {
    if (!is_object($object)) {
      unset($objects[$key]);
    }
  }
  return $objects;
}


function _crumbs_get_objects_by_method() {
  $sort_order = _crumbs_get_settings();
  $objects = _crumbs_get_objects();
  foreach ($sort_order as $key => $enabled) {
    if (!$enabled) {
      unset($objects[$key]);
    }
  }
  $objects_by_method = array('.' => array(), 'find' => array());
  foreach ($objects as $k => $object) {
    if (!is_object($object)) {
      continue;
    }
    $objects_by_method['.'][$k] = $object;
    foreach (get_class_methods($object) as $method) {
      $objects_by_method[$method][$k] = $object;
    }
  }
  return $objects_by_method;
}




