<?php


function crumbs_init() {
  // $data = crumbs_get_breadcrumb_data();
}


function crumbs_perm() {
  return array('administer crumbs');
}


/**
 * Implements hook_menu()
 */
function crumbs_menu() {
  $items = array();
  $items['admin/structure/crumbs'] = array(
    'title' => 'Crumbs',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crumbs_admin_form'),
    'access arguments' => array('administer crumbs'),
    'file' => 'crumbs.admin.inc',
  );
  $items['admin/structure/crumbs/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/structure/crumbs/debug'] = array(
    'title' => 'Debug',
    'page callback' => 'crumbs_debug_page',
    'access arguments' => array('administer crumbs'),
    'file' => 'crumbs.debug.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  return $items;
}


function crumbs_theme() {
  return array(
    'crumbs_breadcrumb_link' => array(
      'item' => NULL,
    ),
  );
}


/**
 * Default theme implementation for theme('crumbs_breadcrumb').
 * The default implementation uses the theme's implementation of
 * theme('breadcrumb').
 * Themes that are crumbs-aware can override this theme hook to ignore
 * theme('breadcrumb'). Such a theme implementation will look much simpler than
 * the default imp.
 */
function theme_crumbs_breadcrumb_link(array $item) {
  return l($item['link_title'], $item['link_path'], $item['link_options']);
}


function crumbs_preprocess_page(&$vars) {
  $breadcrumb_data = crumbs_get_breadcrumb_data();
  $vars['crumbs_trail'] = $breadcrumb_data['trail'];
  // $vars['crumbs_breadcrumb_items'] = $breadcrumb_data['items'];
  // $vars['crumbs_breadcrumb_html'] = $breadcrumb_data['html'];
  $vars['breadcrumb'] = $breadcrumb_data['html'];
  // TODO: Invoke preprocessPage() plugin method.
  $plugin_engine = crumbs_get_plugin_engine();
  $action = new _crumbs_InvokeAction_preprocessPage($vars);
  $plugin_engine->invokeAll_alter($action);
}


function crumbs_process_page(&$vars) {
  // we just let this hook sit here..
}


function crumbs_get_breadcrumb_data() {
  static $_data;
  if (!isset($_data)) {
    $trail = crumbs_get_trail();
    module_load_include('inc', 'crumbs', 'crumbs.breadcrumb');
    $breadcrumb_items = crumbs_build_breadcrumb($trail);
    $router_item = crumbs_get_router_item($_GET['q']);

    // Support for core's breadcrumb api.

    // Allow modules to alter the breadcrumb, if possible, as that is much
    // faster than rebuilding an entirely new active trail.
    drupal_alter('menu_breadcrumb', $breadcrumb_items, $router_item);

    // Don't show a link to the current page in the breadcrumb trail.
    $end = end($breadcrumb_items);
    if ($router_item['href'] == $end['href']) {
      array_pop($breadcrumb_items);
    }

    $links = array();
    foreach ($breadcrumb_items as $i => $item) {
      $links[$i] = theme('crumbs_breadcrumb_link', $item);
    }
    $html = theme('breadcrumb', array(
      'breadcrumb' => $links,
      'crumbs_breadcrumb_items' => $breadcrumb_items,
      'crumbs_trail' => $trail,
    ));
    $items = $breadcrumb_items;
    $_data = compact('trail', 'items', 'html');
  }
  return $_data;
}


function crumbs_get_trail($path = NULL) {
  static $_trails = array();
  if (!isset($path)) {
    $path = $_GET['q'];
  }
  $path = drupal_get_normal_path($path);
  if (!isset($_trails[$path])) {
    module_load_include('inc', 'crumbs', 'crumbs.plugin_engine');
    module_load_include('inc', 'crumbs', 'crumbs.trail');
    $_trails[$path] = crumbs_build_trail($path);
  }
  return $_trails[$path];
}


function crumbs_match_pattern($patterns, $path = NULL) {
  if (is_string($patterns)) {
    $patterns = explode("\n", $patterns);
  }
  if (!isset($path)) {
    $path = $_GET['q'];
  }
  $trail = crumbs_get_trail($path);
  $patterns_normalized = array();
  foreach ($patterns as $pattern) {
    $pattern = trim(strtolower($pattern));
    if (strlen($pattern)) {
      $patterns_normalized[$pattern] = TRUE;
    }
  }
  $patterns = $patterns_normalized;
  foreach (array_reverse($trail) as $item) {
    $alias = $item['alias'];
    if (isset($patterns[$alias])) {
      return TRUE;
    }
    else if (isset($patterns['! '. $alias])) {
      return FALSE;
    }
    else if (isset($patterns[$alias .'/+'])) {
      return TRUE;
    }
    else if (isset($patterns['! '. $alias .'/+'])) {
      return FALSE;
    }
  }
  $alias = drupal_get_path_alias($path);
  $fragments = explode('/', $alias);
  $partial_alias = array_shift($fragments);
  $match = NULL;
  while (TRUE) {
    if (empty($fragments)) break;
    if (isset($patterns[$partial_alias .'/*'])) {
      $match = TRUE;
    }
    else if (isset($patterns['! '. $partial_alias .'/*'])) {
      $match = FALSE;
    }
    $partial_alias .= '/'. array_shift($fragments);
  }
  if (isset($match)) {
    return $match;
  }
  if (isset($patterns['*'])) {
    return TRUE;
  }
  return FALSE;
}


function crumbs_get_plugin_engine() {
  static $_plugin_engine;
  if (!isset($_plugin_engine)) {
    module_load_include('inc', 'crumbs', 'crumbs.plugin_engine');
    $_plugin_engine = _crumbs_load_plugin_engine();
  }
  return $_plugin_engine;
}


/**
 * This function has exactly one possible input value for
 * each possible return value, except the return value FALSE.
 * 
 * @param $router_path :string
 *   The router path can contain any character, but will typically
 *   have a format like "node/%/edit".
 * @return :string or FALSE
 *   A string that can be used as a method suffix,
 *   or FALSE, where that is not possible.
 *   The route "node/%/edit" will resolve as "node_x_edit".
 */
function crumbs_build_method_suffix($router_path) {
  $method_suffix = strtolower($router_path);
  $method_suffix = preg_replace('#[^a-z0-9\%]#', '_', $method_suffix);
  $method_suffix = strtr($method_suffix, array('%' => 'x'));
  $reverse = strtr($method_suffix, array('_' => '/'));
  $reverse = preg_replace(array('#/x/#', '#/x$#'), array('/%/', '/%'), $reverse);
  // we need to do this two time to catch things like "/x/x/x/x".
  $reverse = strtr($reverse, array('/x/' => '/%/'));
  if ($reverse === $router_path) {
    return $method_suffix;
  }
  return FALSE;
}


class _crumbs_InvokeAction_preprocessPage implements crumbs_InvokeActionInterface_alter {

  protected $_vars;

  function __construct(array &$vars) {
    $this->_vars = &$vars;
  }

  /**
   * The point of the preprocessPage() method hook is a guaranteed execution
   * directly after crumbs_preprocess_page().
   */
  function invoke($plugin, $plugin_key) {
    if (method_exists($plugin, 'preprocessPage')) {
      $plugin->preprocessPage($this->_vars);
    }
  }
}


function crumbs_benchmark($label = NULL, $dpm = FALSE) {
  static $_t;
  $t = microtime(TRUE);
  if (isset($_t) && isset($label)) {
    $str = 'Duration: ' . number_format(1000 * ($t-$_t), 3) . ' ms for '. $label;
    if ($dpm) {
      dpm($str);
    }
  }
  $_t = $t;
  return $str;
}


// ============================================ interfaces =====================


interface crumbs_InvokeActionInterface_find {
  function invoke($plugin, $plugin_key, $weight_keeper);
}


interface crumbs_InvokeActionInterface_alter {
  function invoke($plugin, $plugin_key);
}



